//   CipherSeed interop golden vectors — the strongest tests in this repo.
//
//   Every vector below was produced by the OFFICIAL Tari wallet daemon (`tari_ootle_walletd`
//   0.39.0, esmeralda) and cross-checked in both directions:
//
//     D1  a phrase generated by tari-cipherseed, imported into a fresh daemon wallet via
//         `--seed-words`, then `create-account --key-index 0`
//     D2  a phrase generated BY the daemon (`seed-words`), imported into tari-cipherseed
//
//   Both directions produced identical keys, including `view_only_private_key` — a PRIVATE key the
//   daemon exposes directly, so these are private-key agreements, not two implementations landing
//   on the same public point by luck. Addresses were confirmed against Caravel's own shipped
//   ootle-wasm encoder, so the chain is pinned end to end: phrase -> entropy -> keys -> otl_esm_.
//
//   Upstream Tari publishes no known-answer vectors for this format (its own Rust tests are
//   self-consistent round-trips), so these fixtures ARE the external oracle. If one of them ever
//   fails, the recovery-phrase format or the derivation has changed and every wallet created under
//   the old behaviour is affected. Stop and investigate — do not update the expected values.

import { describe, expect, it } from 'vitest'
import { Network } from '@tari-project/ootle'
import { SecretKeyWallet } from '@tari-project/ootle-secret-key-wallet'
import { deriveAccountKeys, importWalletSeed } from 'tari-cipherseed'

const hex = (b: Uint8Array) => [...b].map(x => x.toString(16).padStart(2, '0')).join('')

interface Vector {
  label: string
  mnemonic: string
  ownerPublicKey: string
  viewPrivateKey: string
  viewPublicKey: string
  address: string
}

// D1 — phrases generated by tari-cipherseed, verified by importing into the daemon.
const PACKAGE_TO_DAEMON: Vector[] = [
  {
    label: 'D1-0',
    mnemonic:
      'leopard shove teach odor aim ginger atom occur siren avoid hungry hidden cannon mistake electric material lawsuit manage gym slight where list soon hover',
    ownerPublicKey: 'e692325a4528d687ad7b6ff9efed43c98f794be1979f56558d8f90681d6fe771',
    viewPrivateKey: 'b30d0ba8627107efefd795db0a6f021e04f6a290974b1f97bc2e7ca78f36fe00',
    viewPublicKey: '9afd90d00a3147d59dc059f1a9f9a4242b096cea0396acb0a9d9844940907d4d',
    address:
      'otl_esm_1u6frykj99rtg0ttmdlu7lm2rex8hjjlpj704v4vd37gxs8t0uace4lvs6q9rz374nhq9nudflxjzg2cfdn4q894vkz5anpzfgzg86ngha863h',
  },
  {
    label: 'D1-1',
    mnemonic:
      'cake edge usual omit blanket boy combine slim exact debris eternal elevator maid hero angle sunset logic outside shy mistake stay game useless client',
    ownerPublicKey: 'b437ce84a9e2bffe46a6865601d118c3d03ff5112d2d0abbd2da3234df132133',
    viewPrivateKey: 'f6e344a2758d9444e0fd5564ba214aac684e7305709d02b0bf8b2de866822e00',
    viewPublicKey: 'e49707ae2bb9775a0f39d8e72eb454f142bd03d3260e62b06c68a1fa488af072',
    address:
      'otl_esm_1ksmuap9fu2llu34xsetqr5gcc0grlag395ks4w7jmgerfhcnyye7f9c84c4mja66puua3eewk320zs4aq0fjvrnzkpkx3g06fz90qusjvagz9',
  },
  {
    label: 'D1-2',
    mnemonic:
      'leopard fish soccer calm north fire quit plastic price announce print match normal vague myself what stone creek unfair else prefer annual maximum output',
    ownerPublicKey: '62d7e97b76279f79974d155a1d5ba8db65908710c532e6e0431ce28df9948832',
    viewPrivateKey: '4aef9126d04749e9d4d005e5fd6db083a0f809762dba3599b951e219ccc7c507',
    viewPublicKey: 'e2bf4912be66ab48a65e4738bce15dd6e55185cea3d197a12e257ee0d145c60d',
    address:
      'otl_esm_1vtt7j7mky70hn96dz4dp6kagmdjeppcsc5ewdczrrn3gm7v53qew906fz2lxd26g5e0yww9uu9wade23sh8285vh5yhz2lhq69zuvrgaddp06',
  },
  {
    label: 'D1-3',
    mnemonic:
      'leopard meadow very scene climb afraid gather any detail detail pepper birth butter ignore hire tooth unfold inside rural arrange spirit wrestle dilemma ensure',
    ownerPublicKey: 'b61a753839f2356a30f4a161d1ea9c6f24193e366dc5f330f50cd17f9939f67f',
    viewPrivateKey: 'b54dc658ab69ba8fd61b9803ce7dcf67a23af740a1676a1bdb242b44dc5d690b',
    viewPublicKey: 'f0e7adff0ce547c84b95603c091509a5b9bc34cc14f8f07dea9d72257d2c6018',
    address:
      'otl_esm_1kcd82wpe7g6k5v8559sar65udujpj03kdhzlxv84pnghlxfe7ellpeadluxw237gfw2kq0qfz5y6twduxnxpf78s0h4f6u3905kxqxqpzdc7l',
  },
  {
    label: 'D1-4',
    mnemonic:
      'gate lion polar glory aim power nest accuse reopen muffin income pig winter theory magnet wealth office notable memory guilt offer tiny pet observe',
    ownerPublicKey: '0c138a2207b94c60441322ea9bffde11ab762b7e67f0aeb86b3356f8f019947b',
    viewPrivateKey: 'f48101c0cd451a93ec8ca03d73e447be03be13865e5dca91236643a76ab17600',
    viewPublicKey: '28d0d8ec28fa4d04eab96075e3dbf284332f299f3a92dbda56a50c7ae6c6726b',
    address:
      'otl_esm_1psfc5gs8h9xxq3qnyt4fhl77zx4hv2m7vlc2awrtxdt03uqej3aj35xcas505ngya2ukqa0rm0eggve09x0n4ykmmft22rr6umr8y6cm26xyu',
  },
]

// D2 — phrases generated BY the daemon, verified by importing into tari-cipherseed. This direction
// is the one that proves a user can bring an existing official Tari wallet into Caravel.
const DAEMON_TO_PACKAGE: Vector[] = [
  {
    label: 'D2-0',
    mnemonic:
      'doctor wolf absent home video edit dust credit spike bike gorilla exhaust enemy exit cause match vast found boat three average inch giraffe involve',
    ownerPublicKey: 'f8c9302a9d93d9b33d20f28de5b5557c7ee4496cc33d7ae19524a79b7479215e',
    viewPrivateKey: '2307098f0b59da8cca735b3bcfbc3dfef185361ed0459dd60290087afdb6610e',
    viewPublicKey: '5ed705bd2af46af00c084dacb48d33487641a853a3556c6b25b54ee81ccd8747',
    address:
      'otl_esm_1lrynq25aj0vmx0fq72x7td2403lwgjtvcv7h4cv4yjnekarey909a4c9h540g6hspsyymt9535e5sajp4pf6x4tvdvjm2nhgrnxcw3cys646k',
  },
  {
    label: 'D2-1',
    mnemonic:
      'gate deal weasel occur forum luggage hold tired dress agent craft acquire spy absorb hidden midnight purpose soldier layer violin vapor art addict crush',
    ownerPublicKey: 'd0dbcf9f61598694f023f6c21c9c96b15164434aa48c1405f6f1d0f022e8493f',
    viewPrivateKey: '9dec809958b80a4c1c0d25d727e5412eedf7483b0a098666b7b9ef8e5109a70f',
    viewPublicKey: '1a00a52ed6f85ed2749a240c951fe0d68999560262b52cb6693fb8a01cd4eb05',
    address:
      'otl_esm_16rdul8mptxrffupr7mppe8ykk9gkgs625jxpgp0k78g0qghgfyl35q999mt0shkjwjdzgry4rlsddzve2cpx9dfvke5nlw9qrn2wkpgu2qsx6',
  },
  {
    label: 'D2-2',
    mnemonic:
      'gate split school pyramid winner assume quick cover zebra duty purchase black cage save claim uniform thumb private stem fine sleep gas prosper avocado',
    ownerPublicKey: '321fb26325352b8310c824cd0aee61c5177b426120c1f162ba313488cfce5565',
    viewPrivateKey: '3e8f7e95438447f0e120c47ac2d619994ac3ea9a0eafdd949ec313ac18bc6602',
    viewPublicKey: '50242dd7fe7744d2b552ff5b4a197bad920e3ce23a6ad911d2a5d9d95da2472d',
    address:
      'otl_esm_1xg0myce9x54cxyxgynxs4mnpc5thksnpyrqlzc46xy6g3n7w24j4qfpd6ll8w3xjk4f07k62r9a6mysw8n3r56kez8f2tkwetk3ywtg4j9aup',
  },
  {
    label: 'D2-3',
    mnemonic:
      'cake release era permit salon tongue episode raw output share any wool elder pony wool explain soon toast seed lawsuit antique negative puppy supply',
    ownerPublicKey: '0e692e84a118317a17473654829fba3432a851b26c6e9221110a050966068661',
    viewPrivateKey: '819be4c61bd098ce7b2dfc29c8116a7742cac839a876479ceb9c60e8eca7ec04',
    viewPublicKey: '4c2e27dca40abccfd9b0d7787d9e4640274ad7064a2d06d03d96f0720805702e',
    address:
      'otl_esm_1pe5jap9prqch5968xe2g98a6xse2s5djd3hfygg3pgzsjesxses5ct38mjjq40x0mxcdw7raneryqf626ury5tgx6q7edurjpqzhqtszs02ej',
  },
  {
    label: 'D2-4',
    mnemonic:
      'able caution child other assault pool stereo ghost worry exhibit hand science rib enough bread very basic vault immense scale size banana marriage quit',
    ownerPublicKey: 'ae1a2d01d9bdde3123ef171e439a2451571eb73c39e2259eef3a639b99161f42',
    viewPrivateKey: '2ccc11c41088b2d78fd858fb20bf0995811c77a27b3859a66a4347f45f587a03',
    viewPublicKey: 'c23100cbc50eceb4c963703c342710f5dccd2ca6a0b4da08f823f39d7615d34b',
    address:
      'otl_esm_14cdz6qwehh0rzgl0zu0y8x3y29t3adeu883zt8h08f3ehxgkrapvyvgqe0zsan45e93hq0p5yug0thxd9jn2pdx6pruz8uuawc2axjcc3vs5a',
  },
]

// Rebuilds the account exactly the way the app will: phrase -> entropy -> index-0 key pair -> the
// same SecretKeyWallet the rest of Caravel already consumes.
async function deriveFromPhrase(mnemonic: string) {
  const seed = await importWalletSeed(mnemonic)
  const { ownerSecret, viewSecret } = deriveAccountKeys(seed.entropy, 0)
  const wallet = SecretKeyWallet.fromSecretKey(ownerSecret, Network.Esmeralda, viewSecret)
  return {
    ownerPublicKey: hex(await wallet.getPublicKey()),
    viewPrivateKey: hex(viewSecret),
    viewPublicKey: hex(await SecretKeyWallet.fromSecretKey(viewSecret, Network.Esmeralda).getPublicKey()),
    address: await wallet.getAddress(),
  }
}

describe.each([
  ['package -> official daemon', PACKAGE_TO_DAEMON],
  ['official daemon -> package', DAEMON_TO_PACKAGE],
] as const)('CipherSeed interop: %s', (_direction, vectors) => {
  it.each(vectors)(
    '$label reproduces the daemon-reported keys and address',
    async vector => {
      const derived = await deriveFromPhrase(vector.mnemonic)
      expect(derived.ownerPublicKey).toBe(vector.ownerPublicKey)
      // The private view key the daemon prints — a private-key match, not just a public one.
      expect(derived.viewPrivateKey).toBe(vector.viewPrivateKey)
      expect(derived.viewPublicKey).toBe(vector.viewPublicKey)
      expect(derived.address).toBe(vector.address)
    },
    30_000,
  )
})

// On first start with an imported phrase the daemon does not derive one account — it sweeps key
// indices upward, registering each, and marks the FIRST as the default. These are the ten accounts
// it recovered for the D1-0 phrase. Pinning all ten proves the index mapping is right across the
// whole recovery range rather than coincidentally right at zero, and index 0 is the one Caravel
// derives because it is the account the official wallet actually presents.
const DAEMON_RECOVERY_SWEEP = [
  'e692325a4528d687ad7b6ff9efed43c98f794be1979f56558d8f90681d6fe771', // 0 — daemon's DEFAULT
  '685dd513d785066b06c3ad41637b7766f018f95e103ddf9fe55d6c694cdf0b51',
  'c620e789f4740eb8a873e804a1848e15a8c53128e424eafc658866438422ed17',
  '1afa431b4ced6db4cce676ec8b26a9b5a3869308eaf704a35d273503e9356c48',
  'c0aac78f8661c23599bced8222e364f852157100a433718c4fbac5ace37ffb51',
  '4a678c4d94b4082af027231acf583c684068e1cfeff72c1e0105c051c1eb5452',
  'cec093fb271c545c08e5f4a3c72fdf2cffae4932dc16a5b0c22e71690c61267c',
  '6eabb115e2a0507c17449aafc7250577a0fb73c59441586382b3264d2c832460',
  '6c88bfbb63fdb301515ab19205e79014a9917ce274e441b665f351b0db64a324',
  'b4304ccc3314c46f7b6202a84395a33e4e120a2b2b321f9e58b3810453608426',
]

describe('daemon account-recovery sweep', () => {
  it('reproduces every account the daemon recovered, indices 0 through 9', async () => {
    const seed = await importWalletSeed(PACKAGE_TO_DAEMON[0].mnemonic)
    for (let index = 0; index < DAEMON_RECOVERY_SWEEP.length; index++) {
      const { ownerSecret } = deriveAccountKeys(seed.entropy, index)
      const wallet = SecretKeyWallet.fromSecretKey(ownerSecret, Network.Esmeralda)
      expect(hex(await wallet.getPublicKey()), `account index ${index}`).toBe(
        DAEMON_RECOVERY_SWEEP[index],
      )
    }
  }, 30_000)

  // Guards the one number that would strand a wallet without ever looking like an error: derive at
  // the wrong index and an imported phrase opens a real, empty, wrong account.
  it('derives index 0 — the account the official wallet presents as default', async () => {
    const seed = await importWalletSeed(PACKAGE_TO_DAEMON[0].mnemonic)
    const { ownerSecret } = deriveAccountKeys(seed.entropy, 0)
    const wallet = SecretKeyWallet.fromSecretKey(ownerSecret, Network.Esmeralda)
    expect(hex(await wallet.getPublicKey())).toBe(DAEMON_RECOVERY_SWEEP[0])
  }, 30_000)
})
